_target_: src.models.star_baseline.STARModelFull

window: 32
n_sensors: 14
d_model: 128
nhead: 1
num_scales: 3
ffn_dim: 256
patch_size: 4
dropout: 0.25
encoder_layers_per_scale: 4
decoder_layers_per_scale: 2
pos_learnable: true
